import * as React from "react"
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';

import howItWorkImg1 from "../../images//how-it-works/how-it-work4.jpg"
import howItWorkImg2 from "../../images//how-it-works/how-it-work5.jpg"
import howItWorkImg3 from "../../images//how-it-works/how-it-work6.jpg"

const HowItWorks = () => {
  return (
    <>
      <div className="how-it-works-area bg-252029 bg-half-color position-relative z-index1 pt-100 pb-75">
        <Container>
          <div 
            className="section-title text-white"
            data-aos="fade-up"
            data-aos-duration="1200"
            data-aos-delay="100"
            data-aos-once="false"
          >
            <span className="sub-title">How It Works</span>
            <h2>
              Here How It <span>Works</span>
            </h2>
            <p>
              <strong>End to end Compliance Management.</strong> AML tools for all sizes, integrated into one comprehensive suite.
            </p>
          </div>

          <Row className="justify-content-center">
            <Col 
              lg={4} md={6} sm={6}
              data-aos="fade-up"
              data-aos-duration="1200"
              data-aos-delay="100"
              data-aos-once="false"
            >
              <div className="how-it-works-box text-white mb-25">
                <img
                  src={howItWorkImg1}
                  alt="how-it-works"
                />
                <h3>
                  <strong>Load Data <br></br>Transaction</strong> 
                </h3>
                <p>
                    Upload your transaction data to your company application instance using csv file or via the API.
                </p>
              </div>
            </Col>

            <Col 
              lg={4} md={6} sm={6}
              data-aos="fade-up"
              data-aos-duration="1200"
              data-aos-delay="200"
              data-aos-once="false"
            >
              <div className="how-it-works-box text-white mb-25">
                <img
                  src={howItWorkImg2}
                  alt="how-it-works"
                />
                <h3>
                  <strong>Build and Test AMLRules</strong> 
                </h3>
                <p>
                  Use our templates to build your rule library or write your 
                  own rules easily without the need for any coding skills. 
                </p>
              </div>
            </Col>

            <Col 
              lg={4} md={6} sm={6}
              data-aos="fade-up"
              data-aos-duration="1200"
              data-aos-delay="300"
              data-aos-once="false"
            >
              <div className="how-it-works-box text-white mb-25">
                <img
                  src={howItWorkImg3}
                  alt="how-it-works"
                />
                <h3>
                  <strong>Monitor and Inverstigate Alert</strong>
                </h3>
                <p>
                  Deploy the rules to production and investigate cases generated by alerts. 
                  Use the analytical tools to monitor transactions.
                </p>
              </div>
            </Col>
          </Row>
        </Container>
      </div>
    </>
  )
}

export default HowItWorks
